### ISSUE TITLE
No identity transformation for use with non-truncated normal prior

### ISSUE THREAD

**Issue by LGro** [boschresearch/parameterspace#38]
```python
ContinuousParameter(name="param", bounds=(float("-inf"), float("inf")), transformation=None, prior=Normal())
```
results in
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "parameterspace/parameterspace/utils.py", line 35, in wrapper
    init_method(self, *args, **kwargs)
  File "parameterspace/parameterspace/parameters/continuous.py", line 53, in __init__
    super().__init__(
  File "parameterspace/parameterspace/parameters/base.py", line 58, in __init__
    assert np.allclose(
AssertionError: Missmatch between the prior bounds ([-inf  inf])and the transformation's bounds ([0 1])!
```
which seems fair, but there also does not seem to be a way to specify no transformation despite the `ContinuousParameter` docstring saying that `Default transformation is the identity.` - the `IntegerParameter` implementation is likely affected as well.

Do we want to add an identity transformation or drop support for the normal prior and just allow truncated normal, @sfalkner?

**Comment by LGro** [comment]
Since ParameterSpace does not support infinite bounds, the proposal is to:
- [ ] change the docstring to reflect the default `affine-linear transformation of the bounds to [0,1]`
- [ ] raise a meaningful error in case infinite bounds are specified
- [ ] remove support for the non-truncated Normal prior
